spring:
  application:
    name: spring-security-gym
  data-source:
    url: jdbc:mysql://localhost:3307/gym_spring?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    expiration: ${JWT_EXPIRATION:600000}
    key: ${JWT_KEY}